# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12l-IY-a-649PMfHCXvmfeGF41aX3sH9E
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

x = 6 * np.random.rand(100, 1) - 3
y =0.5 * x**2 + 1.5*x + 2 + np.random.randn(100, 1)

plt.scatter(x, y,color="g")

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
regression_1=LinearRegression()

regression_1.fit(X_train,y_train)

plt.plot(X_train,regression_1.predict(X_train),color='r')
plt.scatter(X_train,y_train)

from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(degree=2,include_bias=True)
X_train_poly=poly.fit_transform(X_train)
X_test_poly=poly.transform(X_test)

X_train_poly

regression = LinearRegression()
regression.fit(X_train_poly, y_train)
y_pred = regression.predict(X_test_poly)

plt.scatter(X_train,regression.predict(X_train_poly))
plt.scatter(X_train,y_train)